[phases.build]
cmds = [
  "npm ci",
  "export DATABASE_URL=postgresql://postgres:placeholder@localhost:5432/kado && npx prisma generate && npm run build --workspace=@kado/api"
]

[start]
cmd = "npm run start --workspace=@kado/api"
